// Stable machine-readable error codes returned alongside messages.
// The frontend switches on these — never change a value once shipped.

export const ERROR_CODES = Object.freeze({
  // Auth
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_MISSING: "AUTH_TOKEN_MISSING",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_REFRESH_INVALID: "AUTH_REFRESH_INVALID",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  AUTH_PASSWORD_INCORRECT: "AUTH_PASSWORD_INCORRECT",

  // Users
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_INACTIVE: "USER_INACTIVE",
  USER_DUPLICATE: "USER_DUPLICATE",

  // Generic
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
});

export default ERROR_CODES;
