// Run with both servers active and Playwright installed under the OS temp directory.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { chromium } = require(path.join(os.tmpdir(), 'fdm-browser-tools/node_modules/playwright'));

(async () => {
  const browser = await chromium.launch({ headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    const base = 'http://127.0.0.1:3000';
    const metadataResponse = await page.request.get(`${base}/api/model`);
    assert.equal(metadataResponse.status(), 200);
    const metadata = await metadataResponse.json();
    assert.equal(metadata.groups.flatMap(group => group[1]).length, 26);
    const expected = await (await page.request.post(`${base}/api/predict`, { data: metadata.example })).json();
    assert.equal((await page.request.post(`${base}/api/predict`, { data: {} })).status(), 400);
    assert.equal((await page.request.get(`${base}/api/predict`)).status(), 405);
    assert.equal((await page.request.get(`${base}/api/unknown`)).status(), 404);
    assert.equal((await page.request.post(`${base}/api/predict`, { data: '{', headers: { 'Content-Type': 'application/json' } })).status(), 400);
    const screenshots = path.join(__dirname, '../doc/screenshots/nextjs');
    fs.mkdirSync(screenshots, { recursive: true });
    await page.goto(base);
    const example = page.getByRole('button', { name: 'Load example booking' });
    await example.waitFor();
    await page.locator('#hotel').waitFor();
    await page.screenshot({ path: path.join(screenshots, 'desktop-empty.png') });
    await example.click();
    const submit = page.getByRole('button', { name: 'Assess cancellation risk', exact: true });
    await submit.click();
    await page.locator('#prediction').waitFor();
    assert.equal(await page.locator('#probability').textContent(), `${(expected.cancellation_probability * 100).toFixed(2)}%`);
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: path.join(screenshots, 'desktop-result.png') });
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Download assessment' }).click();
    const downloaded = JSON.parse(fs.readFileSync(await (await downloadPromise).path(), 'utf8'));
    assert.equal(downloaded.assessment.prediction, expected.prediction);
    assert.ok(Math.abs(downloaded.assessment.cancellation_probability - expected.cancellation_probability) < 1e-12);
    assert.equal(downloaded.booking.hotel, metadata.example.hotel);
    await page.locator('#adults').fill('0');
    assert.equal(await page.locator('#prediction').count(), 0);
    // Hide the erroneous section: backend validation must reopen it and focus the field.
    await page.getByRole('button', { name: /Guests & preferences/ }).click();
    await submit.click();
    await page.locator('#error-adults').waitFor();
    assert.match(await page.locator('#error-adults').textContent(), /at least one guest/);
    assert.equal(await page.locator('#adults').getAttribute('aria-invalid'), 'true');
    await example.click();
    await page.locator('#children').fill('');
    await page.locator('#agent').fill('');
    await page.locator('#company').fill('');
    await page.locator('#country').selectOption('');
    await submit.click();
    await page.locator('#prediction').waitFor();
    await page.getByRole('button', { name: 'Model performance', exact: true }).click();
    await page.getByRole('heading', { name: 'Evidence behind the estimate' }).waitFor();
    await page.waitForFunction(() => window.scrollY === 0);
    await page.screenshot({ path: path.join(screenshots, 'performance.png') });
    await page.getByRole('button', { name: 'Assessment guide', exact: true }).click();
    await page.getByRole('heading', { name: 'A more informed next step' }).waitFor();
    await page.getByRole('button', { name: 'Explore an example booking' }).click();
    await page.getByRole('button', { name: 'How it works' }).click();
    await page.getByRole('dialog').waitFor();
    await page.keyboard.press('Escape');
    assert.equal(await page.getByRole('dialog').count(), 0);
    assert.equal(await page.getByRole('button', { name: 'How it works' }).evaluate(button => button === document.activeElement), true);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: path.join(screenshots, 'mobile-form.png'), fullPage: true });
    await submit.click();
    await page.locator('#prediction').waitFor();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await page.screenshot({ path: path.join(screenshots, 'mobile-result.png'), fullPage: true });
    await page.getByRole('button', { name: 'Clear form' }).click();
    assert.equal(await page.locator('#prediction').count(), 0);
    assert.equal(await page.locator('#hotel').inputValue(), '');
    // Explicit service-error and retry path, then reconnect to the real API.
    await page.route('**/api/model', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Service offline for test.' }) }));
    await page.reload();
    await page.getByRole('heading', { name: 'Let’s reconnect the prediction service.' }).waitFor();
    await page.unroute('**/api/model');
    await page.getByRole('button', { name: 'Try again' }).click();
    await page.locator('#hotel').waitFor();
    assert.deepEqual(errors, []);
    console.log('PASS: Next.js proxy, actual prediction parity, all 26 fields, download, stale clearing, collapsed-section validation, optional defaults, navigation, help dialog, mobile layout, reset and service reconnection.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
